#!/usr/bin/python3
import pandas as pd

email = pd.read_csv("colombia.csv")
email['First Name'] = email['First Name'].str.capitalize()
email['First Name'] = email['First Name'].str.split(" ", expand=True)
email["First Name"] = email["First Name"].str.replace(".", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("s.a.s", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("S.A.S", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("SAS", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("S.A", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("S. A.", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("Ltd.", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("Ltda", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("S/A", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("=", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("SAA", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("saa", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace(".", "", regex=False)
email["Company Name"] = email["Company Name"].str.replace("@", "", regex=False)
email['Company Name'] = email['Company Name'].str.split('/', expand=True)
email['Company Name'] = email['Company Name'].str.split('-', expand=True)
email['Company Name'] = email['Company Name'].str.split('(', expand=True)
email['Company Name'] = email['Company Name'].str.split('|', expand=True)
email['Company Name'] = email['Company Name'].str.title()
email['Job Position'] = email['Job Position'].str.split('/', expand=True)
email['Job Position'] = email['Job Position'].str.split('(', expand=True)
email['Job Position'] = email['Job Position'].str.split('|', expand=True)
email["Job Position"] = email["Job Position"].str.replace(".", "", regex=False)
email['Job Position'] = email['Job Position'].str.title()

email.to_csv('colombiaout.csv')