#!/usr/bin/python3
import pandas as pd

email = pd.read_csv("colombia.csv")
email['FirstName'] = email['FirstName'].str.capitalize()
email['FirstName'] = email['FirstName'].str.split(" ", expand=True)
email["FirstName"]= email["FirstName"].str.replace(".", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("s.a.s", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.A.S", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("SAS", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.A", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S. A.", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("Ltd.", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("Ltda", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S/A", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("=", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("SAA", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("saa", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace(".", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("@", "", regex=False)
email['CompanyName'] = email['CompanyName'].str.split('/', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('-', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('(', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('|', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('/', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('(', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('|', expand=True)
email['CompanyName'] = email['CompanyName'].str.title()
email["Position"]= email["Position"].str.replace(".", "", regex=False)
email['Position'] = email['Position'].str.title()

email.to_csv('colombiaout.csv')
