#!/usr/bin/python3
import pandas as pd

email = pd.read_csv("peru.csv")
email['FirstName'] = email['FirstName'].str.capitalize()
email['FirstName'] = email['FirstName'].str.split(" ", expand=True)
email["FirstName"]= email["FirstName"].str.replace(".", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.A.C.", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.A.A.", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.A", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.A", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S. A.", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S A", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("SAC", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("E.i.r.l.", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.r.l.", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.c.r.l", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("Scrl", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("S.r.l", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace(".", "", regex=False)
email["CompanyName"]= email["CompanyName"].str.replace("@", "", regex=False)
email['CompanyName'] = email['CompanyName'].str.split('/', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('-', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('(', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('|', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('/', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('(', expand=True)
email['CompanyName'] = email['CompanyName'].str.split('|', expand=True)
email['CompanyName'] = email['CompanyName'].str.title()
email["Position"]= email["Position"].str.replace(".", "", regex=False)
email['Position'] = email['Position'].str.title()

email.to_csv('peruout.csv')
